### PR TITLE
Small doc fixes

### PR DESCRIPTION
**Pull request by robmen**

### CODE REVIEW

**Review by barnson — CHANGES_REQUESTED** [review]
I'm fairly confident `DotNetCoreSdkFeatureBandSearch/@Version` also needs the version treatment.

**Comment by robmen** [comment]
Okay. That one is using the uber-flexible `WixVersionType` but I'll update it to use the strict-three part type.

**Comment by barnson** [comment]
Those are the only two attributes using `WixVersionType` but refer to .NET (Core) versioning.

**Review by barnson — APPROVED** [review]

**Comment by robmen** [comment]
Also added $(var.) and !(loc.) support.

**Review by rseanhall — APPROVED** [review]

**Pull request merged**
