### PR TITLE
Create 5386-support-msi-transactions.html.md

### PR DESCRIPTION
**Pull request by nirbar**
WIP 5386- Support MSI transactions

### CODE REVIEW

**Comment by barnson** [comment]
Another limitation is that you can't mix 32-bit and 64-bit packages in a transaction.

**Comment by nirbar** [comment]
Is there any other limitation you know of?

**Comment by barnson** [comment]
That's the big one I know of but I've heard it's buggy.

**Comment by nirbar** [comment]
In your opinion, is it too buggy to try or should we give it a chance?

**Comment by barnson** [comment]
I'm not sure. It would have to be opt-in so people could avoid what doesn't work. Then it would be down to deciding whether the behavior differences are worth the benefit. I suggest starting a thread on wix-devs.

**Pull request merged**
