### PR TITLE
Schema documentation

### PR DESCRIPTION
**Pull request by tsahi**
While developing an installer using WiX Toolset, I found the documentation puzzling and far from clear and complete. Often, it seemed like it's using terms only understood by the WiX developers themselves, terms that mean nothing to users.

So I created this branch (and another one), in the hope it will make the documentation clearer. In this pull request the main changes are:
1. Add critical missing information to the Utils schema page. I was using this schema, except fo the default Wix, so that's where I touched. I hope you will make the same change in all schema pages.
2. move repeating text to `howtos/general/extension_usage_introduction.html.md`.
3. Add links to articles in `howtos/general/index.html.md`.

### CODE REVIEW

**Comment by robmen** [comment]
This documentation is all generated from the documentation in the `wix3` project. The `wix.chm` is built as part of the product so you'll want to edit these files here: https://github.com/wixtoolset/wix3/tree/develop/src/chm

**Comment by tsahi** [comment]
Are you kidding me? Then what is this repo for, if it's generated from another repo? This is yet another example of how incomplete the Wix documentation is, because it says nothing about this at http://wixtoolset.org/documentation/manual/v3/wixdev/help_development.html.

But fear not, for yet another pull request is coming your way, this time, explaining exactly what you wrote above.

**Comment by tsahi** [comment]
Would you mind telling me which of the 7 or 8 .sln files in the wix3 repo I should use to build the docs?

**Comment by tsahi** [comment]
Never mind, found it.

**Pull request closed without merging**
