### PR TITLE
Fix entire file being bold

### PR DESCRIPTION
**Pull request by Daniel15**
The final `\` in `c:\Program Files` appeared to escape the `<` in `</strong>`, resulting in the entire page being bold. I just added another slash to escape it.

### CODE REVIEW

**Comment by rseanhall** [comment]
Thanks, but this file is auto generated.  It comes from the wix3 repo in src/chm/documents/howtos/files_and_registry, please make the change there.

**Comment by Daniel15** [comment]
Could you please make that more obvious (eg. with a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates), and/or by adding a comment to the top of the autogenerated files)? Right now it's not obvious that the files need to be edited in a different repo.

**Comment by Daniel15** [comment]
@rseanhall - Could you please make that more obvious (eg. with a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates), and/or by adding a comment to the top of the autogenerated files)? Right now it's not obvious that the files need to be edited in a different repo.

**Comment by Daniel15** [comment]
https://github.com/wixtoolset/wix3/pull/378

**Comment by rseanhall** [comment]
Yeah, we need to figure out a way to do that.

**Pull request closed without merging**
