### PR TITLE
Web site update.

### PR DESCRIPTION
**Pull request by briandrennan**
Re-styled the releases page as discussed in the WiX devs mailing list.

Features:

Independent 'Published' releases page
    * This would still need to be updated between releases (I believe this is how it was done previously?)
Independent 'Weekly' releases page
    * This gets the data the same way it always did

I did not remove the releases.html.cshtml page, but did update the main index references to the folder, and validated all navigation running IISExpress/tinysite locally.

### CODE REVIEW

**Comment by robmen** [comment]
Thanks for doing this. First, can you rebase out all the revert commits?  Something like:
`git rebase -p -i HEAD~6`. When prompted for the commits to keep, delete the middle four commits and change the last (bottom) commit to be a "fixup" instead of a "pick". That should get you down to one nice clean commit.

**Comment by robmen** [comment]
Also, I like the text you added and putting the Published builds on the left looks like a good idea. However, I don't think we make people click through to yet another page to get to the actual releases. I think we can just put the list under the correct columns.

Simply putting Production builds on the left I think is the killer fix here.

Thanks, again. Sorry I missed this commit for so long. I was wondering what happened based on the conversations on wix-devs. :smile_cat:

**Comment by briandrennan** [comment]
Hi @robmen,

I believe that I've fixed it up. Do you mind having a quick review? I also took the comments you had about not requiring navigation to a different area, and consolidated the production releases to the same /releases/ page. Now, getting the unstable builds would require a user to select the link to the weekly builds, but the production-ready ones are ready to go.

I'm near certain I still need to clean up the commit messages, but wanted to get feedback on the layout change as I trek through figuring out the right series of git commands to clean up the commit history.

Thanks!

**Comment by briandrennan** [comment]
Hi @robmen,

I was wondering if you'd had a chance to have a look at this? I know, just based on the mailing list, that you've been extremely busy.

Thanks again for affording me the opportunity to contribute to the project!

**Comment by robmen** [comment]
Sorry, I'm not getting notifications from GitHub and missed both of your replies. Sean just pointed out that I'd missed this PR's updates. Looking now.

**Comment by robmen** [comment]
@briandrennan the commits were a real mess. :)  I squashed everything down and cleaned out a couple deletes you probably didn't intend to make and took this. I'll look to other's feedback about how well they like the weekly releases being on a separate page.

Thanks for working through it all.

**Pull request closed without merging**
